### ISSUE TITLE
Error Access Denied

### ISSUE THREAD

**Issue by scropion86** [edit4ever/script.module.tvh2kodi#1]
Hi,

thanks for your effort to provide such Add-on to ease the use of TVH.
i am totally new to TVH but i created a new user with all the access includes admin and use it fot the PVR add-on also , but same user gives Error "Access denied with your Add-on"
i am using LibreELEC running TVH 4.2
is there any thing i am missing?
regards,

**Comment by edit4ever** [comment]
did you enter the user/password in the addon settings?
