### ISSUE TITLE
LibreElec v10.0.0

### ISSUE THREAD

**Issue by juxuanu** [edit4ever/script.module.tvh2kodi#4]
Trying to install the latest version in the latest Libreelec release (10.0.0) errors out with a message indicating that the addon is not compatible with this version.

**Comment by edit4ever** [comment]
Are yo sure you tried to install the 3.0 release?  I just tested on LE 10.0 master and it installed just fine.

**Comment by juxuanu** [comment]
Sorry, the error message is not very helpful. Once I connected the system to the Internet, it worked.
